# Generated by Django 5.1.4 on 2025-01-02 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_bookmarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmarks',
        ),
    ]
