# Generated by Django 5.1.4 on 2025-01-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_delete_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='bookmarked',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
